projects:
  app:
    schemaPath: "../backend/database/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4444/graphql"
  prisma:
    schemaPath: "../backend/src/generated/prisma.graphql"
    extensions:
      prisma: "../backend/prisma.yml"

